# Generated by Django 3.1.2 on 2020-10-15 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_dieta', '0002_auto_20201014_1750'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dados',
            name='dt_final',
            field=models.DateField(blank=True, null=True, verbose_name='Data Final'),
        ),
        migrations.AlterField(
            model_name='dados',
            name='dt_inicio',
            field=models.DateField(blank=True, null=True, verbose_name='Data Inicial'),
        ),
        migrations.AlterField(
            model_name='dieta',
            name='refeicao',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='Refeição'),
        ),
    ]
